### ISSUE TITLE
wheel creation?

### ISSUE THREAD

**Issue by kkvilekval** [pearu/pylibtiff#120]
We would like to create a specific binary wheel for a particular architecture.  While the setup does have some references to wheels, I am seeing the error below.  We are building in a virtualenv which may be causing the hiccup.  Can anybody confirm that they are able to build a wheel ?

```
copying build/lib.linux-x86_64-3.5/libtiff/lsm.py -> /home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/libtiff
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    setup_package()
  File "setup.py", line 269, in setup_package
    setup(**metadata)
  File "/home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 259, in run
    self.run_command('install')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/numpy/distutils/command/install.py", line 62, in run
    r = self.setuptools_run()
  File "/home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/numpy/distutils/command/install.py", line 36, in setuptools_run
    return distutils_install.run(self)
  File "/usr/lib/python3.5/distutils/command/install.py", line 595, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 15, in run
    self.byte_compile(outfiles)
  File "/usr/lib/python3.5/distutils/command/install_lib.py", line 138, in byte_compile
    dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/util.py", line 450, in byte_compile
    % (file, prefix))
ValueError: invalid prefix: filename '/home/kgk/.virtualenvs/build3/lib/python3.5/site-packages/libtiff/tiff_h_4_0_6.py' doesn't start with 'build/bdist.linux-x86_64/wheel'

```

**Comment by dmoore247** [comment]
I get same error on two platforms (Mac and Ubuntu 16.x)
