### ISSUE TITLE
Python >=3.11.5 ImportError: Failed to find TIFF library

### ISSUE THREAD

**Issue by tham-raven** [pearu/pylibtiff#168]
Apologies if this is a foolish question.
We are attempting to pip pylibtiff into a Windows 10 x64 installation of python 3.11.5 or higher. We have tried 3.11.5, 3.11.6, and 3.12.

The pip install completes successfully:

```
Collecting pylibtiff
  Using cached pylibtiff-0.6.1-cp311-cp311-win_amd64.whl
Requirement already satisfied: numpy>=1.13.3 in c:\users\----------------\.conda\envs\shared_3_11_5\lib\site-packages (from pylibtiff) (1.26.1)
Installing collected packages: pylibtiff
Successfully installed pylibtiff-0.6.1
```

However, when executing imports the code cannot find the .dll that windows requires (it is my novice understanding that libtiff.dll's are for linux and win is looking for tiff.dll). In previous versions of python we do see the appropriate tiff.dll in the site-packages\libtiff directory.
As an alternative to pylibtiff we attempted pip'ing in the libtiff library and allowing the .dll's to be compiled locally but the compile fails every time on a bitarray issue.
Are we doing something wrong?

```
from libtiff import TIFF
Traceback (most recent call last):
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\site-packages\libtiff\libtiff_ctypes.py", line 54, in <module>
    libtiff = ctypes.cdll.LoadLibrary("libtiff.dll")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'libtiff.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\site-packages\libtiff\__init__.py", line 30, in <module>
    from .libtiff_ctypes import libtiff, TIFF, TIFF3D  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\site-packages\libtiff\libtiff_ctypes.py", line 58, in <module>
    raise ImportError('Failed to find TIFF library. Make sure that'
ImportError: Failed to find TIFF library. Make sure that libtiff is installed and its location is listed in PATH|LD_LIBRARY_PATH|..
>>> from libtiff import TIFFfile
Traceback (most recent call last):
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\site-packages\libtiff\libtiff_ctypes.py", line 54, in <module>
    libtiff = ctypes.cdll.LoadLibrary("libtiff.dll")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\--------------\.conda\envs\shared_3_11_5\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'libtiff.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by djhoese** [comment]
A couple things:

1. For formatting blocks of literal text in github comments use 3 backticks before and after the block of text (on their own lines). I've rewritten your post, but feel free to edit it again if the formatting looks wrong.
2. pylibtiff does not bundle the libtiff C/C++ library into its package. Neither the binary wheel nor the source distribution (sdist) have it. You need to have it installed in your environment or on your system and pylibtiff will try to find it at run time.
3. I see from your error messages that you are using conda environments. The `pylibtiff` package is available from the conda-forge channel and would simplify this down to `conda install -c conda-forge pylibtiff`. This assumes you're using conda-forge packages for your entire environment as mixing defaults/main packages with conda-forge, especially with libraries like libtiff-C, can easily cause problems.

**Comment by tham-raven** [comment]
Thank you so much for the quick reply and for the formatting fix. It's my first post so i wasn't familiar with the proper protocol.
Hopefully this one is an improvement.

Regarding the conda environment, we were only temporarily using conda env's as a means of testing in different versions of python.  At the end of the day this will be a system interpreter that is deployed via source control to our teams so everything will be pip'd in and not conda packages. Conda just allowed us to experiment quickly with different combinations.

I understand now about the dll's not being packaged with pylibtiff. Thank you for that explanation. It's hard to know what i should and should not be expecting.

Here is the output we get when trying to install libtiff. I understand if this is beyond the scope of support for pylibtiff, so I appreciate any help you can provide, but also understand if you need me to seek out assistance elsewhere. :) 

```
(shared_3_11_5) C:\>pip install libtiff
Collecting libtiff
  Using cached libtiff-0.4.2.tar.gz (129 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: libtiff
  Building wheel for libtiff (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [173 lines of output]
      C:\Users\----\AppData\Local\Temp\pip-install-f7js5whs\libtiff_d8f8ffa0c5d14c509bc182ba730f501f\setup.py:77: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        from numpy.distutils.core import setup, Extension
      Warning: Assuming default configuration (libtiff\bitarray-a1646c0\bitarray/{setup_bitarray,setup}.py was not found)
      Appending libtiff.bitarray configuration to libtiff
      Ignoring attempt to set 'name' (from 'libtiff' to 'libtiff.bitarray')
      Appending libtiff configuration to
      Ignoring attempt to set 'name' (from '' to 'libtiff')
      0.4.2
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "bittools" sources
      INFO: building extension "tif_lzw" sources
      INFO: building extension "libtiff.bitarray._bitarray" sources
      INFO: building extension "libtiff.bittools" sources
      INFO: building extension "libtiff.tif_lzw" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      C:\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\libtiff_ctypes.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\lsm.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\lzw.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\optparse_gui.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\script_options.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\setup.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\test_bittools.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_array.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_base.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_channels_and_files.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_data.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_file.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_files.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_3_8_2.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_3_9_2.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_3_9_4.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_3_9_5.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_4_0_1.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_4_0_2.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_4_0_3.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_4_0_6.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_4_0_7.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_4_0_8.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_h_4_0_9.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_image.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\tiff_sample_plane.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\utils.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\version.py -> build\lib.win-amd64-cpython-311\libtiff
      copying libtiff\__init__.py -> build\lib.win-amd64-cpython-311\libtiff
      creating build\lib.win-amd64-cpython-311\libtiff\bitarray
      copying libtiff\bitarray-a1646c0\bitarray\test_bitarray.py -> build\lib.win-amd64-cpython-311\libtiff\bitarray
      copying libtiff\bitarray-a1646c0\bitarray\__init__.py -> build\lib.win-amd64-cpython-311\libtiff\bitarray
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1085] : testing flags (/O2)
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda\envs
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda\envs\shared_3_11_5
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda\envs\shared_3_11_5\Lib
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\numpy
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\numpy\distutils
      creating C:\Users\RSMSNT~1\AppData\Local\Temp\tmpsr8y3nat\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\numpy\distutils\checks
      INFO: CCompilerOpt.cc_test_flags[1085] : testing flags (/WX)
      WARN: CCompilerOpt.__init__[1252] : feature 'AVX512_KNL' is disabled, MSVC compiler doesn't support it
      WARN: CCompilerOpt.__init__[1252] : feature 'AVX512_KNM' is disabled, MSVC compiler doesn't support it
      WARN: CCompilerOpt.__init__[1252] : feature 'AVX512_SPR' is disabled, MSVC compiler doesn't support it
      INFO: CCompilerOpt.__init__[1794] : check requested baseline
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'SSE2' with flags ()
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'SSE' with flags ()
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'SSE3' with flags ()
      INFO: CCompilerOpt.__init__[1803] : check requested dispatch-able features
      INFO: CCompilerOpt.cc_test_flags[1085] : testing flags (/arch:AVX)
      INFO: CCompilerOpt.cc_test_flags[1085] : testing flags (/arch:AVX2)
      INFO: CCompilerOpt.cc_test_flags[1085] : testing flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX512_SKX' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'POPCNT' with flags ()
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'SSSE3' with flags ()
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'F16C' with flags (/arch:AVX)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'FMA3' with flags (/arch:AVX2)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX512F' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX2' with flags (/arch:AVX2)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'SSE41' with flags ()
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX' with flags (/arch:AVX)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'SSE42' with flags ()
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX512CD' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX512_CNL' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX512_CLX' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1559] : testing feature 'AVX512_ICL' with flags (/arch:AVX512)
      INFO: CCompilerOpt.__init__[1815] : skip features (SSE3 SSE2 SSE) since its part of baseline
      INFO: CCompilerOpt.__init__[1819] : initialize targets groups
      INFO: CCompilerOpt.__init__[1821] : parse target group simd_test
      INFO: CCompilerOpt._parse_target_tokens[2032] : skip targets (ASIMD VSX3 XOP VSX4 NEON VXE VSX2 FMA4 VX VSX VXE2) not part of baseline or dispatch-able features
      INFO: CCompilerOpt._parse_policy_not_keepbase[2144] : skip baseline features (SSE2)
      INFO: CCompilerOpt.generate_dispatch_header[2365] : generate CPU dispatch header: (build\src.win-amd64-3.11\numpy\distutils\include\npy_cpu_dispatch_config.h)
      WARN: CCompilerOpt.generate_dispatch_header[2374] : dispatch header dir build\src.win-amd64-3.11\numpy\distutils\include does not exist, creating it
      INFO: CCompilerOpt.feature_extra_checks[1639] : Testing extra checks for feature 'AVX512F' (AVX512F_REDUCE)
      INFO: CCompilerOpt.feature_extra_checks[1639] : Testing extra checks for feature 'AVX512_SKX' (AVX512BW_MASK AVX512DQ_MASK)
      INFO: building 'bittools' extension
      INFO: compiling C sources
      creating build\temp.win-amd64-cpython-311\Release\libtiff
      creating build\temp.win-amd64-cpython-311\Release\libtiff\src
      INFO: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -IC:\Users\----\.conda\envs\shared_3_11_5\include -IC:\Users\----\.conda\envs\shared_3_11_5\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tclibtiff/src/bittools.c /Fobuild\temp.win-amd64-cpython-311\Release\libtiff\src\bittools.obj
      INFO: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\----\.conda\envs\shared_3_11_5\libs /LIBPATH:C:\Users\----\.conda\envs\shared_3_11_5 /LIBPATH:C:\Users\----\.conda\envs\shared_3_11_5\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64 /EXPORT:PyInit_bittools build\temp.win-amd64-cpython-311\Release\libtiff\src\bittools.obj /OUT:build\lib.win-amd64-cpython-311\bittools.cp311-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-311\Release\libtiff\src\bittools.cp311-win_amd64.lib
      INFO: building 'tif_lzw' extension
      INFO: compiling C sources
      INFO: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -IC:\Users\----\.conda\envs\shared_3_11_5\include -IC:\Users\----\.conda\envs\shared_3_11_5\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tclibtiff/src/tif_lzw.c /Fobuild\temp.win-amd64-cpython-311\Release\libtiff\src\tif_lzw.obj
      INFO: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\----\.conda\envs\shared_3_11_5\libs /LIBPATH:C:\Users\----\.conda\envs\shared_3_11_5 /LIBPATH:C:\Users\----\.conda\envs\shared_3_11_5\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64 /EXPORT:PyInit_tif_lzw build\temp.win-amd64-cpython-311\Release\libtiff\src\tif_lzw.obj /OUT:build\lib.win-amd64-cpython-311\tif_lzw.cp311-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-311\Release\libtiff\src\tif_lzw.cp311-win_amd64.lib
      INFO: building 'libtiff.bitarray._bitarray' extension
      INFO: compiling C sources
      creating build\temp.win-amd64-cpython-311\Release\libtiff\bitarray-a1646c0
      creating build\temp.win-amd64-cpython-311\Release\libtiff\bitarray-a1646c0\bitarray
      INFO: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -IC:\Users\----\.conda\envs\shared_3_11_5\include -IC:\Users\----\.conda\envs\shared_3_11_5\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tclibtiff\bitarray-a1646c0\bitarray\_bitarray.c /Fobuild\temp.win-amd64-cpython-311\Release\libtiff\bitarray-a1646c0\bitarray\_bitarray.obj
      _bitarray.c
      libtiff\bitarray-a1646c0\bitarray\_bitarray.c(148): error C2106: '=': left operand must be l-value
      libtiff\bitarray-a1646c0\bitarray\_bitarray.c(175): error C2106: '=': left operand must be l-value
      libtiff\bitarray-a1646c0\bitarray\_bitarray.c(196): error C2106: '=': left operand must be l-value
      libtiff\bitarray-a1646c0\bitarray\_bitarray.c(1380): warning C4996: 'PyEval_CallObjectWithKeywords': deprecated in 3.9
      libtiff\bitarray-a1646c0\bitarray\_bitarray.c(1519): warning C4996: 'PyEval_CallObjectWithKeywords': deprecated in 3.9
      libtiff\bitarray-a1646c0\bitarray\_bitarray.c(3036): error C2106: '=': left operand must be l-value
      libtiff\bitarray-a1646c0\bitarray\_bitarray.c(3037): error C2106: '=': left operand must be l-value
      error: Command "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\----\.conda\envs\shared_3_11_5\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -IC:\Users\----\.conda\envs\shared_3_11_5\include -IC:\Users\----\.conda\envs\shared_3_11_5\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tclibtiff\bitarray-a1646c0\bitarray\_bitarray.c /Fobuild\temp.win-amd64-cpython-311\Release\libtiff\bitarray-a1646c0\bitarray\_bitarray.obj" failed with exit status 2
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[863] : write cache to path -> C:\Users\----\AppData\Local\Temp\pip-install-f7js5whs\libtiff_d8f8ffa0c5d14c509bc182ba730f501f\build\temp.win-amd64-cpython-311\Release\ccompiler_opt_cache_ext.py
```

**Comment by djhoese** [comment]
Ah ok, I see where some of the confusion is. So pylibtiff (this repository) is a python library that tries to access "libtiff". libtiff is a C library (maybe C++) and will show up on systems as `.so` (linux), `.dylib` (mac), `.dll` (windows), or some similar concept. This library doesn't come "bundled" in the python library for a couple reasons including that it is a large project and that many other pieces of software depend on. So usually this library is installed with some sort of package manager. On linux you'll often see instructions for installing it with a package manager like `yum` or `apt`. On mac I think it comes with some version of libtiff, but you'll also see instructions for third-party package managers like homebrew or macports. For Windows...I have the least experience so I don't know many options. I know of "chocolatey" (https://chocolatey.org/), but I'm also sure there is a semi-standard way to install something like libtiff (the C library). This is why I was relieved that you were using conda because conda is not only a python package manager but a general purpose package manager and is able to install C/C++/fortran/etc libraries in addition to Python or Ruby tools.

Now, as for why `pip install libtiff` did *something* instead of immediately error'ing out: there was a period of time for this project where it was renamed to "libtiff" on the PyPI package repository (where `pip install` looks by default). This was reverted and the project is again published as "pylibtiff". I think it's been long enough that no one should be dependent on "libtiff" on PyPI, so maybe we could convince @pearu to delete/archive that version of the package to avoid confusion going forward. Regardless, you won't be able to `pip install` "libtiff" the C library (which pylibtiff depends on) because it is not a Python package. Unlike "conda" or the other package managers I described above, "pip" is only a Python package manager and nothing else. Sometimes we (the users) get lucky when python projects bundled libraries internally and we can pip install them without having to have an additional installation (ex. pyproj can bundle the PROJ library, shapely can bundle the geos library, etc), but pylibtiff is not one of those.

So I'm not sure what the best approach is for you, but you'll need to decide how you'll install non-python dependencies. It may mean googling Windows-compatible package managers or figuring out how libtiff (the C library) suggests Windows users install it on their systems.

**Comment by tham-raven** [comment]
Now things are starting to become more clear. I really appreciate your in depth explanation.
I was under the misunderstanding that the libtiff dll's were either packaged or would be built during the pip installation.
I also see now how I got to that incorrect understanding.
When I installed the libtiff python library years ago into our python 3.8.16 interpreter I used a .whl file from this site:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pylibtiff
These wheels do include the C binaries. Since I had used pip to install that wheel years ago successfully with it deploying the binaries during install, I had assumed (incorrectly) that using pypi to pip in pylibtiff would garner the same result.
Interesting enough, there are .whl's on that site for pylibtiff for python 3.10 which do work and do deploy the libtiff binaries at the same time.
This doesn't solve my python 3.11 problem, but I've got an alternative and certainly a ton more answers to when i first started.
I'm so grateful for your assistance, and I'll close this out as it is clearly not a pylibtiff issue.
btw, I see that you're over at UW Madison. We're based over in Middleton. Small world neighbor :)

**Comment by djhoese** [comment]
> btw, I see that you're over at UW Madison. We're based over in Middleton. Small world neighbor :)

Haha nice! Feel free to join the MadPy group (Madison's Python meetup group that I'm a co-organizer of).

I do want to add one more piece of context. You will sometimes find packages that have Python extensions, and pylibtiff has some, where there are C (or similar) files along side the python `.py` files and these get compiled at install time. In those cases you'll see the `.so`/`.dll` files in the install location. In the case of wheels these C files are pre-compiled and the `.so`/`.dll` files are included in the wheel itself. But these are just "extensions" and are almost never the actual upsteam C/C++ (ex. libtiff, GDAL, PROJ, etc).

**Comment by pearu** [comment]
In past, pylibtiff assumed that Windows users could download libtiff DLL files/installers from https://gnuwin32.sourceforge.net/packages/tiff.htm.

Nowadays, using conda on Windows would be the easiest way to get the libdiff DLL file.

However, when not using conda, a workaround is to manually copy the DLL file from a libtiff conda package (different versions are available [here](https://anaconda.org/conda-forge/libtiff/files)). For example, https://anaconda.org/conda-forge/libtiff/4.6.0/download/win-64/libtiff-4.6.0-h6e2ebb7_2.conda contains a file `pkg-libtiff-....tar.zst` from which `Library/bin/tiff.dll` can be extracted.

**Comment by djhoese** [comment]
C libraries and generally anything not-python should go in the `lib` directory (on linux) which I suspect is the `Lib` directory in your particular Windows environment you're using. The `site-packages` is specifically for python packages and their own extensions/modules. The shared libraries have to be somewhere that python's ctypes package expects to find C/C++ shared libraries.

Glad you at least got something working.
