### ISSUE TITLE
The 'ascii' encoding cannot open images whose file names contain special characters

### ISSUE THREAD

**Issue by yangyunlv** [pearu/pylibtiff#176]
Test environment：
win10 
python3.8.10
pylibtiff0.4.4
filename: 483×55³MDI.tif  

site-packages\libtiff\libtiff_ctypes.py", line 489, in open
tiff = libtiff.TIFFOpen(filename, mode.encode('ascii'))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

![image](https://github.com/pearu/pylibtiff/assets/122206917/f57af1d5-4878-46c5-b905-dd3938d22d28)

**Comment by djhoese** [comment]
The `.encode('ascii')` is on the `mode` argument, not the filename. Something earlier on or perhaps what you're actually passing to `.open` seems to be wrong. Could you provide the actual code you are providing? Do you have a longer/fuller traceback for the exception?

**Comment by yangyunlv** [comment]
If there is no ³, it can be read normally

`from libtiff import TIFF
path = r"C:\Users\Yang\Desktop\483×55³MDI.tif"
image = TIFF.open(path)
`
Traceback (most recent call last):
  File "D:\python\file_tools\test.py", line 5, in <module>
    image = TIFF.open(path)
  File "D:\python\file_tools\lib\site-packages\libtiff\libtiff_ctypes.py", line 489, in open
    tiff = libtiff.TIFFOpen(filename, mode.encode('ascii'))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
Warning: filename argument is of wrong type or encoding: 'gbk' codec can't encode character '\xb3' in position 28: illegal multibyte sequence

**Comment by djhoese** [comment]
Ok so this has nothing to do with the `ascii` encoding. Due to the historic error handling of pylibtiff the failed encoding is only shown as a printed warning (the one that mentions `gbk`). The later error about an incorrect argument type (ArgumentError/TypeError) comes after when an exception is passed to `TIFFOpen`.

A lot of this code has been updated but apparently not released. Could you try installing pylibtiff from the github master branch and see if you get a different result?

**Comment by yangyunlv** [comment]
I updated to 0.6.1, but I don't have the libtiff.dll file, I don't know where to download a valid dll file, I once downloaded one, but it doesn't seem to be the right file. 😂

**Comment by yangyunlv** [comment]
I found a dll file that was available, and after testing it still couldn't read the special characters correctly
![image](https://github.com/pearu/pylibtiff/assets/122206917/d586ee65-5eea-4f38-a574-a374cbaf3b3c)

When I change the file name to normal, the following message appears
![image](https://github.com/pearu/pylibtiff/assets/122206917/c09d54d9-d1b3-4b44-8b73-d943e4947bba)

I do not know if it is a new feature, but this situation is not encountered in version 0.4.4

**Comment by djhoese** [comment]
You have to pip install from the source code to generate the dll.

**Comment by djhoese** [comment]
I'm not sure I fully understand, but I realize you might be talking about the libtiff dll for the C libtiff library and not anything from pylibtiff, right? I also don't understand what situations worked for you and which ones didn't.

Just like the other filename issue you created (#152) some of these issues seem to be some disconnect/conflict between your python installation and your filesystem. The github master version of pylibtiff should be doing everything correctly as far as I understand and remember to be handling non-ascii filenames the best way possible. I'm not sure how else to test these types of things since a lot of them seem to be specific to your system.

**Comment by yangyunlv** [comment]
I'll try again and see what the problem is

**Comment by yangyunlv** [comment]
Ok, so does pylibtiff support reading byte objects? I want to avoid file name problems by converting images to byte objects.

**Comment by yangyunlv** [comment]
I used TIFFfile instead and it reads the special characters normally
