### ISSUE TITLE
Remove bitarray, bittools and lzw.py

### ISSUE THREAD

**Issue by pearu** [pearu/pylibtiff#95]
Bittools should be moved to a new project.
Bitarray can be just deleted as it is maintained elsewhere.

**Comment by pearu** [comment]
Before removing these modules, make one release that implements deprecation warnings:
```
libtiff.bitarray will be removed, use upstream bitarray instead, see https://github.com/ilanschnell/bitarray
libtiff.bittools will be removed, use bittools from  https://github.com/pearu/bittools
lzw.py will be removed, use tif_lzw extension module instead
```

**Comment by igg** [comment]
Because there is no bitarray dependency listed, installing this (i.e. 51d6f2a) in a clean python 3 environment causes a ModuleNotFoundError upon import:
```
>>> import libtiff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/igg/Projects/viqi/src/venv3/lib/python3.6/site-packages/libtiff/__init__.py", line 35, in <module>
    import bitarray as _bitarray    # noqa: F402
ModuleNotFoundError: No module named 'bitarray'
```
